### ISSUE TITLE
What's the recommended installation approach for aarch64 server?

### ISSUE THREAD

**Issue by rayx** [kata-containers/documentation#352] opened 2019-01-23 07:59 UTC
I followed the manual installation steps for CentOS:

https://github.com/kata-containers/documentation/blob/master/install/centos-installation-guide.md

But there is only a x86_64 directory at http://download.opensuse.org/repositories/home:/katacontainers:/releases:/. 

I checked Ubuntu instructions also. Its document points to the same URL.

Does that mean I need to build from source?

**Comment by jodh-intel** [comment] 2019-01-23 09:43
Hi @rayx - thanks for raising! This is in fact a duplicate of #254. I think your best bet at this stage is to install Kata for arm64 using a snap:

- https://snapcraft.io/kata-containers

---

But this is a good reminder that we need to start creating standard packages for other architectures as documented on:

- https://github.com/kata-containers/packaging/issues/118
- https://github.com/kata-containers/packaging/issues/195

Ping @marcov (OBS), @jcvenegas (packaging), @Pennyzct (ARM), @nitkon (ppc64le), @alicefr (s390x) - we don't have an open issue for zSeries packages afaik?

**Comment by Pennyzct** [comment] 2019-01-23 10:15
Hi~ @rayx @jodh-intel sorry, I have still waited for legal approval to working on OBS packaging. maybe we should add extra arch-dependent info [here](https://github.com/kata-containers/documentation/blob/master/install/ubuntu-installation-guide.md), in case similar issue has been brought up again.

**Comment by jodh-intel** [comment] 2019-01-23 11:01
Hi @Pennyzct - I agree that would be helpful and logical. But since the install docs are actually executed and need to be as simple as possible, it may be better to put an architecture matrix in:

- https://github.com/kata-containers/documentation/tree/master/install

That way, the install docs remain as simple (and similar) as possible.

I think we were all hoping we'd have OBS packages up and running for all architectures imminently (so we didn't include such a matrix initially). Do you have a feel for how close we are to getting the required legal approval?

**Comment by marcov** [comment] 2019-01-23 14:40
thanks for the ping @jodh-intel.

FYI recently I worked on packaging Kata Containers in a way that suits openSUSE requirements and to have packages for x86, ARM, powerpc and s390.

[You can have a look at these packages on OBS](https://build.opensuse.org/project/show/devel:kubic:katacontainers), and, if you are on openSUSE or Fedora 29, you can even try them. I tested them on openSUSE x86 and ARM so far.

There are some difference compared to the official kata packages in the way the various components are built and distributed. [You can find more info here](http://lists.katacontainers.io/pipermail/kata-dev/2018-December/000616.html).

I will soon resume the work of making these packages the official ones for openSUSE, so one day it will be possible to install Kata on openSUSE with just `<PKG_MANAGER> install katacontainers`

**Comment by alicefr** [comment] 2019-01-24 13:15
@jodh-intel @marcov should I create an issue for s390x?

**Comment by jodh-intel** [comment] 2019-01-24 13:25
Hi @alicefr - I think that would be useful for tracking purposes.

**Comment by dtischler** [comment] 2019-04-16 05:07
Is Snap still the recommended method for installing on Aarch64, or are other options now available?  Happy to test if there are newer ways to go about this.  Thanks!

**Comment by grahamwhaley** [comment] 2019-04-16 09:04
@Pennyzct @marcov - any update on aarch64 kata packaging for @dtischler and @rayx ? thx!

**Comment by marcov** [comment] 2019-04-23 10:36
@grahamwhaley from my side there aren't plans to have aarch64 builds of the official Kata packages. This is because in my opinion the way the official Kata packages are structured now does not scale well with supporting multiple architectures. That's why [I started from "scratch"](https://build.opensuse.org/project/show/devel:kubic:katacontainers) for openSUSE. 

Maybe the best thing to do is to discuss this in one of our weekly meetings and see what others think about it.

**Comment by jodh-intel** [comment] 2019-04-24 10:00
@marcov - Agreed. I suggest adding an agenda item to https://etherpad.openstack.org/p/katacontainers-2019-architecture-committee-mtgs.

**Comment by Pennyzct** [comment] 2019-04-24 10:19
Hi~ @jodh-intel @marcov @grahamwhaley sooooooo sorry for the delayed response, I have confirmed with colleagues who are working on OBS, he was telling me that he finally got the legal approval of this OBS and will online the OBS very soon. ;)

**Comment by stevecapperarm** [comment] 2019-04-26 07:05
Hello. I have been looking at porting over the OBS master recipes to AArch64:
https://build.opensuse.org/project/show/home:stevecapper:branches:home:katacontainers:releases:x86_64:master

Do the changes look reasonable?

The biggest stumbling block I have come across is with the filesystem image. IIUC this is a manually uploaded tar ball (from the osbuilder repo?) to the kata-containers-image package. I can't upload binaries manually so need some way to auto generate them.

With OBS I would suspect Kiwi should be used?

**Comment by jodh-intel** [comment] 2019-04-26 08:46
Thanks @stevecapperarm - @marcov, @jcvenegas - could you tal please? ^^

**Comment by marcov** [comment] 2019-04-26 09:22
@stevecapperarm the packaging repo has all it needs to generate a binary image and upload it on OBS.
Alternatively, you can manually build your image with osbuilder and upload it using `osc`:
```
$ osc add file.bin
$ osc ci
```
---------------
A quick and dirty way to get a multiarch package for kata-containers-image is to:
- specify as many `Source: <arch>.tar.gz` lines as the architectures you plan to support,
- untar them all in dedicated folders,
- in the `%install` section, do a `%ifarch` to pick the correct binary to include in the rpm.

**Comment by stevecapperarm** [comment] 2019-04-26 09:37
Thanks @marcov  :-),  the issue with uploading a binary is not a technical one (sorry I should have made that clearer). For security reasons we generally avoid uploading pre-compiled binaries and instead contribute source code/build logic. (I can run through osbuilder fine on a test system, and produce an initrd and img with Alpine rootfs and kata-agent).

**Comment by marcov** [comment] 2019-04-26 13:56
...oh now it's clear :flushed: 

I agree with your concerns. 

For the "soon to be" SUSE packages, I am using kiwi as you correctly proposed (TAL  [here](https://build.opensuse.org/package/show/devel:kubic:katacontainers:images/katacontainers-image-leap)). It requires some tricks to correctly generate an rpm, but it's perfectly doable.

**Comment by egernst** [comment] 2020-04-03 20:27
<refresh>

@stevecapperarm @Pennyzct anything we can do to push this forward?

**Comment by stevecapperarm** [comment] 2020-04-06 09:10
Hi,
I have a recent work in progress fork at: https://build.opensuse.org/project/show/home:stevecapper:branches:home:katacontainers:releases:x86_64:stable-1.10

The kata-containers-image package is blank for AArch64 currently though. We can't upload binary tarballs.

To move this forward I had a couple of ideas:

1. We could package osbuilder and create the initrd + rootfs as a post-install step?
2. We could kiwi up a rootfs + initrd, if so, would the openSUSE Tumbleweed one (just an initrd with some distro .ko's included?) be ok?

What should the kata-containers-image package look like ideally?

(I am refreshing my understanding of kiwi in the meantime and tinkering)

**Closed** 2021-04-07 08:59 UTC
Labels: architecture-specific
